# Generated by Django 5.1.6 on 2025-03-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text='Укажите страну', max_length=20, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Введите номер телефона', max_length=15, null=True, verbose_name='Номер телефона'),
        ),
    ]
