# Generated by Django 5.1.6 on 2025-02-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_at',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
    ]
