# Generated by Django 5.1.6 on 2025-03-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_unpublish_product', 'Can unpublish product'), ('can_delete_product', 'Can delete product')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
