# Generated by Django 5.1.6 on 2025-03-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_unpublish_product', 'Can unpublish product')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
